name: ozmap

services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    ports:
      - "3003:3003"
    env_file: "../.env"
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    env_file: "../.env"


volumes:
  mongodb_data:
