name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27021:27017
        env:
          MONGO_INITDB_DATABASE: ozmap
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Create .env file
        run: |
          cat > .env << EOL
          SERVER_PORT=3003
          NODE_ENV=test
          MONGO_BASE_URI=mongodb://127.0.0.1:27021/oz-tech-test
          LOG_LEVEL=error
          CORS_ORIGIN=http://localhost:3000
          CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS
          CORS_CREDENTIALS=true
          RATE_LIMIT_MAX=100
          RATE_LIMIT_WINDOW=60000
          MONGO_INITDB_DATABASE=ozmap
          EOL

      - name: Run tests
        run: bun test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build server
        run: bun run build

      - name: Build seed script
        run: bun run build:seed

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7
